version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_citas
    restart: always
    environment:
      MYSQL_DATABASE: plataforma_citas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./diagramas/script.sql:/docker-entrypoint-initdb.d/init.sql