# Base de datos H2 en memoria (Cero instalación)
spring.datasource.url=jdbc:mysql://localhost:3306/plataforma_citas?useSSL=false&serverTimezone=America/El_Salvador&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Generar tablas automáticamente desde tus entidades Java
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Consola visual para revisar la BD en el navegador
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console